### ISSUE TITLE
About grid_sample

### ISSUE THREAD

**Issue by MaxLin3104** [jchibane/ndf#11]
https://github.com/jchibane/ndf/blob/8dd9f59c4f3e54d51770aec14a46e562f12a2da7/models/local_model.py#L106

Hi, jchibane, 
In Pytorch document, it's said that **_grid specifies the sampling pixel locations normalized by the input spatial dimensions. Therefore, it should have most values in the range of [-1, 1]. For example, values x = -1, y = -1 is the left-top pixel of input, and values x = 1, y = 1 is the right-bottom pixel of input._**

The range of query points here is [-0.5, 0.5].
Don't we need to normalize the range of query points to [-1,1] here, which means that adding  "p = p * 2" before this line?

Best,
Max Lin

**Comment by jchibane** [comment]
Hi @MaxLin3104 ,

correct, we do the transformation in the preprocessing step already.
To see the full transformation have a look at
https://github.com/jchibane/ndf/blob/8dd9f59c4f3e54d51770aec14a46e562f12a2da7/dataprocessing/boundary_sampling.py#L38

Best,
Julian

**Comment by MaxLin3104** [comment]
Got it! Thanks!
