### ISSUE TITLE
Grid_coords 

### ISSUE THREAD

**Issue by antonyvan** [jchibane/ndf#19]
Hello, Julian,
Thank you for sharing your code. It is a wonderful work. 
I am trying to running your code. and meet one issue about data preparation. 
I see that in boundary_sampling.py  we have this 
       
        grid_coords = boundary_points.copy()
        grid_coords[:, 0], grid_coords[:, 2] = boundary_points[:, 2], boundary_points[:, 0]
        grid_coords = 2 * grid_coords

boundary_points are the points that you mentioned in the paper to compute distance to the surface.  Indeed, we see that ground truth  df = np.abs(igl.signed_distance(boundary_points, mesh.vertices, mesh.faces)[0])    is distance of boundary_points to the mesh.  In theory, we should use **boundary_points**  in training.py 
but  why do you use grid_coords in the decoder instead of **boundary_points** shown as follows?   

          p = batch.get('grid_coords').to(device)
          df_gt = batch.get('df').to(device) #(Batch,num_points)
          inputs = batch.get('inputs').to(device)
         df_pred = self.model(p,inputs) #(Batch,num_points

and why **grid_coords**  switch x and z coordinates, and scaled by 2x ?  **Grid_coords** is misaligned with **inputs**. right ? 
Thanks a lot for your time.
Best regards
Antony

**Comment by jchibane** [comment]
Hey,
this is just the coordinate transformation understood by pytorch grid_sample function and a necessary step to extract the features at the correct positions.
Best,
Julian
