### ISSUE TITLE
The variable 'boundary_samples_npz' misses the key 'df'.

### ISSUE THREAD

**Issue by zhaofang0627** [jchibane/ndf#2]
Hi Julian,

I am trying to train NDF on other datasets. To generate data for training, I use data processing scripts provided in [if-net](https://github.com/jchibane/if-net). However, it seems that the key 'df' in the variable 'boundary_samples_npz' is not computed by if-net. 

https://github.com/jchibane/ndf/blob/10e8aca482eb8de930c0217969c1db724efb5b2a/models/data/voxelized_data_shapenet.py#L67

Could you provide the code of training data generation for NDF? Thanks a lot!

**Comment by jchibane** [comment]
Hi @zhaofang0627 ,

yes, preprocessing scripts will follow soon. IF-Net scripts can not directly be applied, your finding is correct: IF-Net works on occupancy ground truth whereas NDF trains on unsigned distance field samples.

Best,
Julian
