### ISSUE TITLE
Algorithm 1 vs. code

### ISSUE THREAD

**Issue by kampelmuehler** [jchibane/ndf#20]
1) In Algorithm 1 in the paper there is a single value for δ. In the code there are 3 different values if I am not mistaken.

![grafik](https://user-images.githubusercontent.com/9306799/148961766-8fb4de02-e928-4fd7-9db8-91bc18dcdc20.png)
https://github.com/jchibane/ndf/blob/570d7704f7d7dcb45170b1f1bff2936ac456cbee/models/generation.py#L58

![grafik](https://user-images.githubusercontent.com/9306799/148962207-f38ea15d-98c8-40f9-bffb-36bff381a501.png)
https://github.com/jchibane/ndf/blob/570d7704f7d7dcb45170b1f1bff2936ac456cbee/models/generation.py#L61

![grafik](https://user-images.githubusercontent.com/9306799/148962400-008ed61a-fff2-4306-8811-19bd6933cdb4.png)
https://github.com/jchibane/ndf/blob/570d7704f7d7dcb45170b1f1bff2936ac456cbee/models/generation.py#L56

2) Also
 
![grafik](https://user-images.githubusercontent.com/9306799/148961766-8fb4de02-e928-4fd7-9db8-91bc18dcdc20.png)
https://github.com/jchibane/ndf/blob/570d7704f7d7dcb45170b1f1bff2936ac456cbee/models/generation.py#L58
is happening before the refinement in the algorithm and after the refinement in the code.

or is

![grafik](https://user-images.githubusercontent.com/9306799/148961766-8fb4de02-e928-4fd7-9db8-91bc18dcdc20.png)

actually referring to 

https://github.com/jchibane/ndf/blob/570d7704f7d7dcb45170b1f1bff2936ac456cbee/models/generation.py#L40 ?

What is 

https://github.com/jchibane/ndf/blob/570d7704f7d7dcb45170b1f1bff2936ac456cbee/models/generation.py#L58

then?

Can you please clarify?

**Comment by jchibane** [comment]
Hello @kampelmuehler ,
for 1: the published code has the final setup, that we found to work best.
for 2: Line 58 is what you are looking for. This is a loop - so in the first iteration, no refinement was done.

Best,
Julian

**Comment by kampelmuehler** [comment]
Hi Julian,

thanks for having a looK! I don't quite understand what you mean by you answer to 2. It is indeed a loop, but the first thing happening in the loop is the refinement loop. Can you then just point me towards what line 40 is represented by in the algorithm?
