### ISSUE TITLE
the checkpoints .tar file can not been extracted 

### ISSUE THREAD

**Issue by wangfudong** [jchibane/ndf#3]
Hi,
 I found that the file 

> "checkpoint_108h:5m:50s_389150.3971107006.tar"

  stroed in _"experiments/pretrained_dist-0.01_0.49_0.5_sigmas-0.08_0.02_0.003_res-256/checkpoints"_ can not been extracted. 
I used the command 

> 'tar -xvf checkpoint_108h:5m:50s_389150.3971107006.tar'

 but just failed.

Maybe this .tar file has been destroyed, could you update a new file?

**Comment by jchibane** [comment]
Hi @wangfudong,

the checkpoint file is specific to PyTorch and doesn't need to be unzipped - PyTorch handles the saving and loading itself.

Best,
Julian
