### ISSUE TITLE
Could you offer the obj/off files of the dataset?

### ISSUE THREAD

**Issue by ApisXia** [jchibane/ndf#4]
Hello,

I hope to do some test on your dataset and compare to the original obj/off models.

The dataset you used contains 5750 objects. However, the dataset I found in the If-Net project is only 3091. And the overlap is roughly 2400.

So could you help to give us the entire dataset or tell us where to download them?

Thank you.

**Comment by jchibane** [comment]
Hi @ApisXia ,

sure, for IF-Net we used the data from the DISN [Xu et. al. NeurIPS'19] paper:
https://drive.google.com/drive/folders/1QGhDW335L7ra31uw5U-0V7hB-viA0JXr

for NDF we used the original ShapeNet data.

The preprocessing scripts to create the data yourself will follow next week.

Best,
Julian

**Comment by ApisXia** [comment]
Thank you so much!
Looking forward to the preprocessing scripts.

Best.

**Comment by ApisXia** [comment]
Hello,

I am so sorry that I find the car subset in the link you give just contain 3091 objects. However, the dataset you used is 5750.
Does it mean I should combine multiple subsets of different cars?

Thank you.

**Comment by jchibane** [comment]
Hi @ApisXia,

as mentioned above, the link I provided was used for the IF-Net paper.

For NDF please consider downloading from the original source https://www.shapenet.org .

Best,
Julian

**Comment by ApisXia** [comment]
Thank you for your reply.

We have downloaded the shapenet from the original source. However, in both core v1 and core v2, the total number of car objects is 3533, which is far less than the dataset you used.

Could you help us with that?

**Comment by jchibane** [comment]
Hi,

we used ShapeNet.core.v1 class 02958343 see for example here:
http://shapenet.cs.stanford.edu/shapenet/obj-zip/ShapeNetCore.v1/02958343/
which has in total 7497 objects.  
For some objects the first attempt of preprocessing failed, and we worked with the successfully preprocessed subset. I expect using all objects will improve generalizability of the model.

Best,
Julian
