### ISSUE TITLE
Questions about data preprocessing

### ISSUE THREAD

**Issue by XuyangBai** [jchibane/ndf#5]
Hi Julian,

Thanks for your sharing. I have two questions regarding the data preprocessing part:

1. What is `sample_sigmas` represents?  At the beginning, I thought the `boundary_{sigma}_samples.npz` file saves the sampled points around the surface with UDF as a Gaussian distribution of mean=0 and std=sigma, but I load some of them and find they are not. Could you explain a little bit about these three files?
2. I find the `voxelized_point_cloud_256res_10000points.npz` file contains a field called `compressed_occupancies` which save the occupancy of a 256 * 256 * 256 voxel grid. But I am confused about what is the occupancy of an open surface? Is is just a voxelization of the input sparse point cloud? I think you mentioned in the paper that SDF and occupancy are not well defined for open surfaces.

Besides, would you mind share the data preprocessing code? Thanks a lot in advance.

Best,
Xuyang.

**Comment by jchibane** [comment]
Hi @XuyangBai ,

1.) Well, your assumption is actually exactly correct. We sample points with a Gaussian distribution around surface points. We find their ground truth unsigned distance and train the NDF network using this information.

2.) This is for the experiment where the input to the network is a voxelized point cloud. The task of the network is, given this input data, to complete the missing shape. Basically Point Cloud Completion, where the point cloud is voxelized into a grid. For each point in the point cloud, its closest voxel is set to 1, all other voxels are set to 0.
So this does not encode inside / outside but the location of the points of a 3D point cloud.

Yes, preprocessing code will soon follow. I had to finish other duties beforehand unfortunately, I'm sorry for this!

Best,
Julian
