### ISSUE TITLE
Could you share the code for computing surface normals?

### ISSUE THREAD

**Issue by zhaofang0627** [jchibane/ndf#7]
Hi Julian,

Thanks for your excellent work! Could you share the code for computing surface normals as described in Section 3.4  of the paper?

Thank you!

**Comment by jchibane** [comment]
Hi @zhaofang0627 ,

thanks! Yes, we plan to upload the code for rendering and normal computation in the next weeks.

Best,
Julian

**Comment by gdwei** [comment]
> Hi @zhaofang0627,
> 
> thanks! Yes, we plan to upload the code for rendering and normal computation in the next weeks.
> 
> Best, Julian

Hi Julian,

Could you share the code for rendering? 

Thank you!
